import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <header className="bg-green-700">
          <nav className="flex justify-end p-2 gap-2">
            <Link href="/">Home</Link>
            <Link href="/cart">Cart</Link>
            <Link href="/auth/login">Login</Link>
            <Link href="/auth/register">Register</Link>
          </nav>
        </header>

        <main className="bg-gray-500 flex-1">
          {children}
        </main>

        <footer className="flex bg-green-700 justify-center">
          <h1>Footer</h1>
        </footer>
        
      </body>
    </html>
  );
}
